blueprint:
  name: GOE surplus controller blueprint
  description: A Blueprint for the automation needed for the surplus controller to work
  domain: automation
  author: Matin114

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - select.custom_chargeprio
    id: prioChanged
  - platform: state
    entity_id:
      - sensor.go_echarger_217953_lbp
    id: buttonPressed
  - platform: time_pattern
    seconds: /10
    id: timeTrigger


action:
  - service: goecharger_mqtt.goe_surplus_controller
    data:
      triggerId: "{{trigger.id}}"