set_config_key:
  name: Set config key
  description: Sets a config key to a provided value.
  fields:
    serial_number:
      name: Serial number
      description: The serial number of the go-e device.
      example: 012345
      required: true
      selector:
        text:
    key:
      name: Config key
      description: The key of the config parameter you want to change.
      example: fna
      required: true
      selector:
        select:
          options:
            - acp
            - acs
            - ama
            - amp
            - ara
            - ate
            - att
            - awc
            - awe
            - awp
            - awpl
            - bac
            - cch
            - cco
            - cfi
            - cid
            - clp
            - ct
            - cwc
            - cwe
            - dwo
            - esk
            - fna
            - frc
            - fup
            - hsa
            - hws
            - ids
            - Key
            - lmo
            - loe
            - lof
            - log
            - lop
            - lot
            - loty
            - lse
            - map
            - mca
            - mci
            - mcpd
            - mcpea
            - mptwt
            - mpwst
            - nmo
            - psmd
            - sch_satur
            - sch_sund
            - sch_week
            - sdp
            - spl3
            - su
            - sua
            - sumd
            - tds
            - tof
            - tse
            - trx
            - upo
            - ust
            - utc
            - wak
            - wan
            - wen
            - wifis
    value:
      name: Value
      description: The new value to set for this config parameter.
      example: "go-e"
      required: true
      selector:
        text:
goe_surplus_controller:
  name: GO-E Charger surplus controller
  description: This service calculates depending on the chargePriority a the power, the GO-E charger may use
  fields:
    globalGrid:
      name: Global Grid
      description: The current global consumed energy in W
      required: true
      selector:
        text:
    batteryPower:
      name: Battery Power
      description: The either charging or discharging load of the battery in W
      required: true
      selector:
        text:
    batteryCurrent:
      name: Battery Current
      description: The current of the charging/discharging battery load A
      required: true
      selector:
        text:
    batteryVoltage:
      name: Battery Voltage
      description: The voltage of the charging/discharging battery load V
      required: true
      selector:
        text:
    batterySOC:
      name: Battery State of Charge
      description: The charge level of the battery in %
      required: true
      selector:
        text: